# Generated by Django 5.2.8 on 2025-11-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_numero_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tempo_estimado',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
